#!/bin/sh

terminator
sleep 1

xdotool key ctrl+shift+e

xdotool type "cd ~/Documents/Projects"
xdotool key Return

xdotool type pwd 
xdotool key Return

xdotool key ctrl+shift+o

xdotool type "cd ~/Documents/Projects/hisaab"
xdotool key Return

xdotool type "code ."
xdotool key Return
